### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by dosten** [javiereguiluz/EasySlugger#2]
I'm reviewing the code and i can see some things that can be improved:
- The logic of `uniqueSlugify` is repeated in all the sluggers, must be good to implement that logic in a `AbstractSlugger`.
- Create a `DEFAULT_SEPARATOR` in the `SluggerInterface` and use it.
- Remove the `static` keyword from the `slugify` and `uniqueSlugify` methods in favor of a `SluggerFactory`

**Comment by javiereguiluz** [comment]
@dosten thanks for proposing improvements to this library!

I'm going to think about the first two points, but the last one looks a no go for me. It's too complicated for such a simple library like this.
